### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by siobhanellis** [sskmy1024y/homebridge-assistant-ui#5]
Installed with Config-UI

ERROR LOADING PLUGIN homebridge-assistant-ui:
[1/6/2021, 8:50:16 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-assistant-ui/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:181:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:120:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:118:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)

**Comment by sskmy1024y** [comment]
@siobhanellis  Thanks for submitting the issue.
I've released 0.0.1-beta.14, which fixes this issue, on npm. Please give it a try.

**Comment by siobhanellis** [comment]
Error: The requested platform 'homebridge-assistant-ui' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/lib/pluginManager.js:152:23)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:271:45
    at Array.forEach (<anonymous>:null:null)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:260:31)
    at Server.start (/usr/local/lib/node_modules/homebridge/lib/server.js:73:35)
    at cli (/usr/local/lib/node_modules/homebridge/lib/cli.js:88:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

**Comment by sskmy1024y** [comment]
@siobhanellis 
Thanks for trying.
However, I was not able to reproduce the same error with my environment.
I tried with a macOS 10.15 and RaspberryPi (Ubuntu). homebrige and other plugins are up to date.

Please let me know your environment.
Also, is this error shown in the config-ui screen?

**Comment by siobhanellis** [comment]
macOS 11.1 on a Macmini

Everything is up to date.

Homebridge V1.2.5
Nodes 14.3.0
Nom 6.14.7

It seems to me the problem is how it gets added to the config.json, that homebridge-assistant-ui is not recognised.

I also saw:

Error loading platform requested in your config.json at position 7

These errors are in my log, which is shown on the main screen of Homebridge UI

So, the issue seems to be that the platform is not loaded.

Siobhan

On Jan 7, 2021, at 9:30 AM, sho yamashita <notifications@github.com<mailto:notifications@github.com>> wrote:



@siobhanellis<https://github.com/siobhanellis>
Thanks for trying.
However, I was not able to reproduce the same error with my equipment.
I tried with a RaspberryPi with macOS 10.15 and Ubuntu. homebrige and other plugins are up to date.

Please let me know your environment.
Also, is this error shown in the config-ui screen?

**Comment by siobhanellis** [comment]
OK, it is because platform, in config.json, needs to be assistant-ui, not homebridge-assistant-ui

Now getting more errors:

[Nest] 42059   - 01/07/2021, 2:16:45 PM   [NestFactory] Starting Nest application...
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +63ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [InstanceLoader] TypeOrmModule dependencies initialized +2ms
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [InstanceLoader] AppModule dependencies initialized +0ms
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [InstanceLoader] ConfigModule dependencies initialized +1ms
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [InstanceLoader] LayoutModule dependencies initialized +0ms
[Nest] 42059   - 01/07/2021, 2:16:45 PM   [InstanceLoader] AuthModule dependencies initialized +0ms

And

[Nest] 42213   - 01/07/2021, 2:20:02 PM   [TypeOrmModule] Unable to connect to the database. Retrying (3)... +3001ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:05 PM   [TypeOrmModule] Unable to connect to the database. Retrying (4)... +3077ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:08 PM   [TypeOrmModule] Unable to connect to the database. Retrying (5)... +3114ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:11 PM   [TypeOrmModule] Unable to connect to the database. Retrying (6)... +3120ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:15 PM   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3087ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:18 PM   [TypeOrmModule] Unable to connect to the database. Retrying (8)... +3137ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:21 PM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3139ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 42213   - 01/07/2021, 2:20:21 PM   [ExceptionHandler] No connection options were found in any orm configuration files. +1ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)

On Jan 7, 2021, at 9:30 AM, sho yamashita <notifications@github.com<mailto:notifications@github.com>> wrote:



@siobhanellis<https://github.com/siobhanellis>
Thanks for trying.
However, I was not able to reproduce the same error with my equipment.
I tried with a RaspberryPi with macOS 10.15 and Ubuntu. homebrige and other plugins are up to date.

Please let me know your environment.
Also, is this error shown in the config-ui screen?

**Comment by sskmy1024y** [comment]
@siobhanellis 
I understand this problem and have published a fix (v0.0.1-beta.16) .

I also tried it using macOS11.1, but I didn't get any TypeOrmModule errors. This has been fixed by 0.0.1-beta.14.
Please try uninstalling homebridge-assistant-ui once and then install it again.

![image](https://user-images.githubusercontent.com/16918590/103961815-a7fa2700-5198-11eb-8a7f-9e1ca9a00003.png)

**Comment by siobhanellis** [comment]
Still getting errors:

[Nest] 63392   - 01/07/2021, 11:24:58 PM   [NestFactory] Starting Nest application...
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [TypeOrmModule] Unable to connect to the database. Retrying (1)... +60ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [InstanceLoader] TypeOrmModule dependencies initialized +1ms
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [InstanceLoader] AppModule dependencies initialized +1ms
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [InstanceLoader] ConfigModule dependencies initialized +0ms
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [InstanceLoader] LayoutModule dependencies initialized +0ms
[Nest] 63392   - 01/07/2021, 11:24:58 PM   [InstanceLoader] AuthModule dependencies initialized +1ms
[Nest] 63392   - 01/07/2021, 11:25:01 PM   [TypeOrmModule] Unable to connect to the database. Retrying (2)... +3144ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:04 PM   [TypeOrmModule] Unable to connect to the database. Retrying (3)... +3103ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:07 PM   [TypeOrmModule] Unable to connect to the database. Retrying (4)... +3132ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:10 PM   [TypeOrmModule] Unable to connect to the database. Retrying (5)... +3132ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:13 PM   [TypeOrmModule] Unable to connect to the database. Retrying (6)... +3149ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:17 PM   [TypeOrmModule] Unable to connect to the database. Retrying (7)... +3110ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processTimers (internal/timers.js:489:9)
[Nest] 63392   - 01/07/2021, 11:25:20 PM   [TypeOrmModule] Unable to connect to the database. Retrying (8)... +3088ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:23 PM   [TypeOrmModule] Unable to connect to the database. Retrying (9)... +3060ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)
[Nest] 63392   - 01/07/2021, 11:25:23 PM   [ExceptionHandler] No connection options were found in any orm configuration files. +1ms
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/connection/ConnectionOptionsReader.js:35:35)
    at step (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:141:27)
    at Object.next (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:122:57)
    at fulfilled (/usr/local/lib/node_modules/homebridge-assistant-ui/node_modules/typeorm/node_modules/tslib/tslib.js:112:62)

**Comment by sskmy1024y** [comment]
@siobhanellis 
Thank you for trying again and again. I am very grateful for your help.

But unfortunately, I cannot reproduce your error.
Could you please help me with the following questions?

- How did you install the plugin? (npm or config-ui-x)
- Is your mac an M1 processor?

And, please check to see file exists `/usr/local/lib/node_modules/homebridge-assistant-ui/dist/ormconfig.js`. 
If it does not exist, you may have an older version installed.

I will continue my investigation. Thank you so much.

**Comment by siobhanellis** [comment]
*   npm version 6.14.7
  *   nodejs version 14.3.0
  *   How did you install the plugin? (npm or config-ui-x) config-ui-x
  *   Is your mac an M1 processor? No

And, please check to see file exists /usr/local/lib/node_modules/homebridge-assistant-ui/dist/ormconfig.js. - Yes it does
